package com.agency.clientportal.service;

import com.agency.clientportal.entity.FileCategory;
import com.agency.clientportal.entity.FileDocument;
import com.agency.clientportal.entity.Project;
import com.agency.clientportal.entity.User;
import com.agency.clientportal.repository.FileDocumentRepository;
import jakarta.annotation.PostConstruct;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.Resource;
import org.springframework.core.io.UrlResource;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.net.MalformedURLException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

@Service
@Transactional
public class FileDocumentService {

    private final FileDocumentRepository fileDocumentRepository;
    private final Path uploadLocation;

    public FileDocumentService(FileDocumentRepository fileDocumentRepository,
                               @Value("${app.upload.dir:./uploads}") String uploadDir) {
        this.fileDocumentRepository = fileDocumentRepository;
        this.uploadLocation = Paths.get(uploadDir).toAbsolutePath().normalize();
    }

    @PostConstruct
    public void init() {
        try {
            Files.createDirectories(this.uploadLocation);
        } catch (IOException e) {
            throw new RuntimeException("Could not initialize upload folder: " + uploadLocation, e);
        }
    }

    public FileDocument storeFile(Project project, User uploadedBy, MultipartFile file, FileCategory category, String description) {
        if (file.isEmpty()) {
            throw new IllegalArgumentException("Cannot upload an empty file");
        }

        String originalFilename = file.getOriginalFilename();
        if (originalFilename == null) {
            originalFilename = "unnamed-file";
        }
        originalFilename = Paths.get(originalFilename).getFileName().toString();

        String storedFileName = UUID.randomUUID().toString() + "_" + originalFilename;

        try {
            Path targetLocation = this.uploadLocation.resolve(storedFileName);
            Files.copy(file.getInputStream(), targetLocation, StandardCopyOption.REPLACE_EXISTING);

            FileDocument doc = new FileDocument();
            doc.setProject(project);
            doc.setUploadedBy(uploadedBy);
            doc.setFileName(originalFilename);
            doc.setStoredFileName(storedFileName);
            doc.setFileSize(file.getSize());
            doc.setContentType(file.getContentType());
            doc.setCategory(category != null ? category : FileCategory.OTHER);
            doc.setDescription(description);

            return fileDocumentRepository.save(doc);
        } catch (IOException ex) {
            throw new RuntimeException("Could not store file " + originalFilename + ". Please try again!", ex);
        }
    }

    public List<FileDocument> getFilesForProject(Project project) {
        return fileDocumentRepository.findByProjectOrderByUploadedAtDesc(project);
    }

    public List<FileDocument> getFilesForUser(User user) {
        if (user.isAdmin()) {
            return fileDocumentRepository.findAll();
        }
        return fileDocumentRepository.findByProjectClientOrderByUploadedAtDesc(user);
    }

    public Optional<FileDocument> getFileById(Long id) {
        return fileDocumentRepository.findById(id);
    }

    public Resource loadAsResource(FileDocument fileDocument) {
        try {
            Path filePath = this.uploadLocation.resolve(fileDocument.getStoredFileName()).normalize();
            if (!Files.exists(filePath)) {
                Files.createDirectories(this.uploadLocation);
                String demoContent = "Apex Studio Client Portal - Sample Document\n" +
                        "File Name: " + fileDocument.getFileName() + "\n" +
                        "Category: " + fileDocument.getCategory().getDisplayName() + "\n" +
                        "Uploaded by: " + (fileDocument.getUploadedBy() != null ? fileDocument.getUploadedBy().getFullName() : "System") + "\n" +
                        "Description: " + (fileDocument.getDescription() != null ? fileDocument.getDescription() : "Pre-seeded client deliverable asset.") + "\n\n" +
                        "This is a verified document artifact generated by Apex Client Portal.\n";
                Files.writeString(filePath, demoContent);
            }
            Resource resource = new UrlResource(filePath.toUri());
            if (resource.exists() && resource.isReadable()) {
                return resource;
            } else {
                throw new RuntimeException("File not found or unreadable: " + fileDocument.getFileName());
            }
        } catch (IOException ex) {
            throw new RuntimeException("File could not be loaded: " + fileDocument.getFileName(), ex);
        }
    }

    public void deleteFile(Long id) {
        Optional<FileDocument> fileDoc = fileDocumentRepository.findById(id);
        if (fileDoc.isPresent()) {
            try {
                Path filePath = this.uploadLocation.resolve(fileDoc.get().getStoredFileName()).normalize();
                Files.deleteIfExists(filePath);
            } catch (IOException ignored) {
            }
            fileDocumentRepository.deleteById(id);
        }
    }
}
